name: Build, Push and Scan the IaC Tools Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "tools/iac/**"
  # pull_request:
  #   branches:
  #     - main
  #   paths:
  #     - "tools/iac/**"

jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/iac-tools:latest
          context: "{{defaultContext}}:tools/iac"
          file: Dockerfile
          provenance: true
          sbom: true

      - name: Scan for vulnerabilities with Docker Scout
        uses: docker/scout-action@v1
        with:
          command: cves, recommendations, compare
          image: ${{ vars.DOCKERHUB_USERNAME }}/iac-tools:latest
          ignore-base: true
          ignore-unchanged: true
          only-fixed: true
