name: Execute Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"

jobs:
  terraform_apply:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    defaults:
      run:
        working-directory: terraform

    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_aws_default_region: ${{ secrets.AWS_DEFAULT_REGION }}
      TF_VAR_connection_host: ${{ secrets.CONNECTION_HOST }}
      TF_VAR_connection_port: ${{ secrets.CONNECTION_PORT }}
      TF_VAR_connection_user: ${{ secrets.CONNECTION_USER }}
      TF_VAR_connection_private_key: ${{ secrets.CONNECTION_PRIVATE_KEY }}
      TF_VAR_hubble_ui_username: ${{ secrets.HUBBLE_UI_USERNAME }}
      TF_VAR_hubble_ui_password: ${{ secrets.HUBBLE_UI_PASSWORD }}
      TF_VAR_hubble_ui_domain: ${{ secrets.HUBBLE_UI_DOMAIN }}
      TF_VAR_main_domain_tls_cert: ${{ secrets.MAIN_DOMAIN_TLS_CERT }}
      TF_VAR_main_domain_tls_key: ${{ secrets.MAIN_DOMAIN_TLS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Set up Kubeconfig
        run: |
          mkdir --parents ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Terraform Init
        id: init
        run: |
          terraform init \
            -input=false \
            -backend-config="bucket=${{ secrets.TERRAFORM_STATE_BUCKET }}" \
            -backend-config="region=${{ secrets.AWS_DEFAULT_REGION }}"

      - name: Terraform Apply
        id: apply
        run: terraform apply -input=false -auto-approve
