name: Execute Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"

jobs:
  terraform_apply:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    defaults:
      run:
        working-directory: terraform

    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_aws_default_region: ${{ vars.AWS_DEFAULT_REGION }}
      TF_VAR_connection_host: ${{ vars.CONNECTION_HOST }}
      TF_VAR_connection_port: ${{ vars.CONNECTION_PORT }}
      TF_VAR_connection_user: ${{ secrets.CONNECTION_USER }}
      TF_VAR_connection_private_key: ${{ secrets.CONNECTION_PRIVATE_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: terraform init \
          -input=false \
          -backend-config="bucket=${{ vars.TERRAFORM_STATE_BUCKET }}" \
          -backend-config="region=${{ vars.AWS_DEFAULT_REGION }}"

      - name: Terraform Apply
        id: apply
        run: terraform apply -input=false -auto-approve
